# Generate PO tracking file

In [159]:
season = "2023FW"
print(season)

2023FW

## Write header for new Shipment Tracking.xlsx file

In [160]:
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Border, Side, Alignment, Protection, Font
thin = Side(border_style = "thin", color = "000000")
thick = Side(border_style = "thick", color = "0033CCCC")
POtrack = Workbook()
POtrack1 = POtrack.active
POtrack1.title = season
POtrack1.merge_cells("A1:J3")
POtrack1["A1"] = season + " China to Global Shipment Tracking"
POtrack1["A1"].font = Font(size = 22, bold = True)
POtrack1["A1"].alignment = center = Alignment(horizontal = "center", vertical = "center", wrap_text = True)
POtrack1.merge_cells("K1:L1")
POtrack1["K1"] = "Country/region"
POtrack1["K1"].alignment = center
POtrack1.merge_cells("K2:L2")
POtrack1["K2"] = "Container"
POtrack1["K2"].alignment = center
POtrack1.merge_cells("K3:L3")
POtrack1["K3"] = "Shipment Details"
POtrack1["K3"].alignment = center
POtrack1.merge_cells("M1:O1")
POtrack1["M1"] = "CA/US"
POtrack1["M1"].font = header = Font(size = 16, bold = True)
POtrack1["M1"].alignment = center
POtrack1["M1"].fill = PatternFill("solid", fgColor = "00008000")
POtrack1.merge_cells("P1:R1")
POtrack1["P1"] = "UK"
POtrack1["P1"].font = header 
POtrack1["P1"].alignment = center
POtrack1["P1"].fill = PatternFill("solid", fgColor = "003366FF")
POtrack1.merge_cells("S1:U1")
POtrack1["S1"] = "DE"
POtrack1["S1"].font = header 
POtrack1["S1"].alignment = center
POtrack1["S1"].fill = PatternFill("solid", fgColor = "00FF9900")
POtrack1.merge_cells("V1:X1")
POtrack1["V1"] = "CN Initial Reserve"
POtrack1["V1"].font = header 
POtrack1["V1"].alignment = center
POtrack1["V1"].fill = PatternFill("solid", fgColor = "00FF0000")
POtrack1.merge_cells("Y1:AA1")
POtrack1["Y1"] = "Wholesaler"
POtrack1["Y1"].font = header 
POtrack1["Y1"].alignment = center
POtrack1["Y1"].fill = PatternFill("solid", fgColor = "00339966")
head = ["PO#",	"CAT", "Season", "Factory", "Total PO in Pcs", "Name", "SKU", "Seasons", "Colour/Graphic(EN)", "Colour/Graphic(CN)", "Remain. in Pcs", "Remain. in %"] + ["PO Plan", "Remain. in Pcs", "Remain. in %"]*5
for col in range(1, 28):
     POtrack1.cell(4, col).value = head[col-1]
     POtrack1.cell(4, col).font = Font(size = 11, bold = True)
     POtrack1.cell(4, col).alignment = center
     POtrack1.cell(4, col).fill = PatternFill("solid", fgColor = "00FFCC00")
     POtrack1.cell(4, col).border = Border(top = thin, bottom = thin, left = thin, right = thin)
POtrack1.row_dimensions[1].border = Border(bottom = thin)
POtrack1.row_dimensions[2].border = Border(bottom = thin)
POtrack1.row_dimensions[3].border = Border(bottom = thin)
POtrack1.column_dimensions['J'].border = Border(right = thin)
POtrack1.column_dimensions['M'].border = Border(left = thick)
POtrack1.column_dimensions['P'].border = Border(left = thick)
POtrack1.column_dimensions['S'].border = Border(left = thick)
POtrack1.column_dimensions['V'].border = Border(left = thick)
POtrack1.column_dimensions['Y'].border = Border(left = thick)
POtrack.save("../PO/" + season + " China to Global Shipment Tracking.xlsx")

## Input PO

In [161]:
import pandas as pd
import numpy as np
import os
from glob import glob
from openpyxl import Workbook
from openpyxl import load_workbook
print(season)

2023FW

#### Read in factory code file and convert to dictionary

In [206]:
factory = pd.read_excel("../PO/1-MasterSKU_CatPrintsFactory.xlsx", sheet_name = 3, skiprows = 2, engine = "openpyxl")
factory.drop(columns = ["Unnamed: 3", "Unnamed: 8", "Unnamed: 9"], inplace = True) 
factory.rename(columns = {"Unnamed: 2": "JSMY"}, inplace=True)
factory["id"] = factory.index
factory = pd.melt(factory, id_vars = "id")
factory.dropna(axis = 0, how = "any")
factory = pd.Series(factory.variable.values, index = factory.value).to_dict()
print(factory)

{'BRC': 'JSKF', 'BTL': 'JSKF', 'BTP': 'JSKF', 'BTT': 'JSKF', 'SWS': 'JSKF', nan: 'JSZT', 'AAA': 'JSMY', 'ACA': 'JSMY', 'ACB': 'JSMY', 'AJS': 'JSMY', 'AHJ': 'JSMY', 'HAV0': 'JSMY', 'HCA0': 'JSMY', 'HCB0': 'JSMY', 'HCF0': 'JSMY', 'HJS': 'JSMY', 'HXP': 'JSMY', 'HBS': 'JSMY', 'HAD0': 'JSMY', 'UT1': 'JSMY', 'UG1': 'JSMY', 'UJ1': 'JSMY', 'UV2': 'JSMY', 'USA': 'JSMY', 'BCV': 'JSMY', 'WJA': 'JSMY', 'WJT': 'JSMY', 'WPF': 'JSMY', 'WPS': 'JSMY', 'WSF': 'JSMY', 'WSS': 'JSMY', 'WBF': 'JSMY', 'KEH': 'JSMY', 'KMT': 'JSMY', 'FJM': 'JSMY', 'FMR': 'JSMY', 'FPM': 'JSMY', 'FSM': 'JSMY', 'XBM': 'JSMY', 'XBK': 'JSMY', 'XLB': 'JSMY', 'XWG': 'JSMY', 'BSA': 'JSMY', 'BSW': 'JSMY', 'IHT': 'JSMY', 'SKB': 'ZJZJ', 'SKG': 'ZJZJ', 'SJF': 'ZJZJ', 'SPW': 'ZJZJ', 'BTB': 'ZJZJ', 'SKX': 'ZJZJ', 'SKT': 'ZJZJ', 'SSS': 'ZJZJ', 'SSW': 'ZJZJ', 'GUA': 'XMRZ', 'GUX': 'XMRZ', 'GHA': 'XMRZ', 'GBX': 'XMRZ', 'WMT': 'JSTQ', 'WRM': 'JSTQ', 'WGS': 'JSTQ', 'ICP': 'JSZT', 'IPS': 'JSZT', 'ISS': 'JSZT', 'ISB': 'JSZT', 'APE': 'JSZT', 'AJA': 'JSZT', 'DRC': 'JSZT', 'LBT': 'JSZT', 'LBP': 'JSZT', 'LAN': 'JSZT', 'LAB': 'JSZT'}

#### Read in masterSKU file

In [163]:
masterSKU = pd.read_excel("../PO/1-MasterSKU-All-Product-2023-11-07.xlsx", sheet_name = 0, skiprows = 1, header = 2, index_col = 9, usecols = "B:M", engine = "openpyxl")
masterSKU.head()

,MSKU Status,Seasons,Seasons SKU,Print SKU,Print Name,Print Chinese,Print Fabric,Size,Category SKU,Adjust SKU,UPC Active
MSKU,,,,,,,,,,,
AAA-AGR-M,Active,"23S,22S,21S","23S,22S,21S",AGR,Army Green,军绿色,NaN,M,AAA,AAA-AGR-M,804928020603
AAA-AGR-L,Active,"23S,22S,21S","23S,22S,21S",AGR,Army Green,军绿色,NaN,L,AAA,AAA-AGR-L,804928020610
AAA-BLK-M,Active,"23S,22S,21S","23S,22S,21S",BLK,Black,黑色,NaN,M,AAA,AAA-BLK-M,804928020641
AAA-BLK-L,Active,"23S,22S,21S","23S,22S,21S",BLK,Black,黑色,NaN,L,AAA,AAA-BLK-L,804928020658
AAA-GRA-M,Active,"23S,22S,21S","23S,22S,21S",GRA,Grey,灰色,NaN,M,AAA,AAA-GRA-M,804928020627

### Read in main PO tracking file

In [218]:
POtrack = load_workbook("../PO/" + season + " China to Global Shipment Tracking.xlsx")[season]
POtrack_df = pd.DataFrame(POtrack.values)
PO_r = POtrack_df.shape[0]
(Detail_r, Detail_c) = POtrack_df.where(POtrack_df.eq("Total PO in Pcs")).stack().index.tolist()[0]
(T_r, T_c) = POtrack_df.where(POtrack_df.eq("Country/region")).stack().index.tolist()[0]
(CA_r, CA_c) = POtrack_df.where(POtrack_df.eq("CA/US")).stack().index.tolist()[0]
(UK_r, UK_c) = POtrack_df.where(POtrack_df.eq("UK")).stack().index.tolist()[0]
(DE_r, DE_c) = POtrack_df.where(POtrack_df.eq("DE")).stack().index.tolist()[0]
(CN_r, CN_c) = POtrack_df.where(POtrack_df.eq("CN Initial Reserve")).stack().index.tolist()[0]
(WS_r, WS_c) = POtrack_df.where(POtrack_df.eq("Wholesaler")).stack().index.tolist()[0]
print(PO_r, Detail_c, T_c, CA_c, UK_c, DE_c, CN_c, WS_c)
print(POtrack_df.iloc[3,])

4 4 10 12 15 18 21 24
0                    PO#
1                    CAT
2                 Season
3                Factory
4        Total PO in Pcs
5                   Name
6                    SKU
7                Seasons
8     Colour/Graphic(EN)
9     Colour/Graphic(CN)
10        Remain. in Pcs
11          Remain. in %
12               PO Plan
13        Remain. in Pcs
14          Remain. in %
15               PO Plan
16        Remain. in Pcs
17          Remain. in %
18               PO Plan
19        Remain. in Pcs
20          Remain. in %
21               PO Plan
22        Remain. in Pcs
23          Remain. in %
24               PO Plan
25        Remain. in Pcs
26          Remain. in %
Name: 3, dtype: object

### Read in PO files

In [219]:
POn = ["P" + str(n) for n in range(203, 204)]
print(POn)

['P203']

In [220]:
file = [y for x in os.walk("../PO/order/") for y in glob(os.path.join(x[0], POn[0] + "*.xlsx"))]
print(file)

['../PO/order/P203 - CA UK EU - WGS - Toasty-Dry Waterproof Snow Glove - 23F\\P203 - CA UK EU - WGS - Toasty-Dry Waterproof Snow Glove 儿童帶指滑雪手套 - 23F.xlsx']

In [222]:
PO = pd.read_excel(file[0], sheet_name = 0, engine = "openpyxl", header = None)
PO.head(11)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,NaN,NaN,货号 Category：,Toasty-Dry Waterproof Snow Glove 儿童帶指滑雪手套 (WGS),NaN,NaN,订单总数量 OrderTotal：,NaN,4118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,订单号 PO#：,P203-2023FW-WGS,NaN,NaN,其中，加拿大 CA：,NaN,3706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,订单日期Order Date：,2022-11-15 00:00:00,NaN,NaN,英国 UK：,NaN,206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,出货日期 Ship Date:,NaN,NaN,NaN,德国 DE：,NaN,206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,For Matt,NaN,Toasty-Dry Waterproof Snow Glove 儿童帶指滑雪手套 (WGS),NaN,NaN,NaN,NaN,NaN,加拿大 订单数量 Canada Order Qty,NaN,NaN,NaN,英国数量 UK Order Qty,NaN,NaN,NaN,德国数量 DE Order Qty,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,销售计划\nSales Plan,2023-,2023-,2023-,销售计划\nSales Plan,2023-,2023-,2023-,销售计划\nSales Plan,2023-,2023-,2023-
7,适应性别,适应年龄,产品编号,英文品名,中文品名,尺码,款式\n版本,订单 \n总数量,加拿大总数量,出货日期 ShipDate\n2023.5.1,出货日期 ShipDate\n2023.8.1,出货日期 ShipDate\n2023.10.1,英国总数量,出货日期 ShipDate\n2023.5.1,出货日期 ShipDate\n2023.8.1,出货日期 ShipDate\n2023.10.1,德国总数量,出货日期 ShipDate\n2023.5.1,出货日期 ShipDate\n2023.8.1,出货日期 ShipDate\n2023.10.1
8,Gender (boy/girl/unisex),Age (younger/older/all),SKU,Colour/Graphic,Colour/Graphic,Size,Design Version,OrderTotal,CA Total Qty,海运数量\nOcean Qty,海运数量\nOcean Qty,海运数量\nOcean Qty,UK Total Qty,UK Total Qty,UK Total Qty,UK Total Qty,DE Total Qty,DE Total Qty,DE Total Qty,DE Total Qty
9,NaN,NaN,总数量 Total Qty：,NaN,NaN,NaN,NaN,4118,3706,3706,0,0,206,206,0,0,206,206,0,0
10,unisex (little more boy),all,WGS-NBB-M,Nebula Blue,恐龙蓝,M,NEW - 新款,300,270,270,NaN,NaN,15,15,NaN,NaN,15,15,NaN,NaN

#### Get the subtotal

In [224]:
# Function: Search value in dataframe, and find the next n non-empty cell
def next_non_empty(df, value, dim, n):
    mask = df.applymap(lambda x: str(value) in str(x)).to_numpy()
    if mask.any():
        r, c = np.argwhere(mask)[0]
    else:
        return df.shape[0]+1, df.shape[1]+1
    if dim == "row":
        for row in range(r+n, df.shape[0]):
            if df.iloc[row, c] is not np.nan: 
                return row, c
                break
    if dim == "col": 
        for col in range(c+n, df.shape[1]):
            if df.iloc[r, col] is not np.nan:
                return r, col
                break

In [244]:
total = PO.iloc[next_non_empty(PO, "OrderTotal", "col", 1)]
try: CA_total = PO.iloc[next_non_empty(PO, "加拿大总数量", "row", 2)]
except (KeyError, IndexError): CA_total = 0
try: UK_total = PO.iloc[next_non_empty(PO, "英国总数量", "row", 2)]
except (KeyError, IndexError): UK_total = 0
try: DE_total = PO.iloc[next_non_empty(PO, "德国总数量", "row", 2)]
except (KeyError, IndexError): DE_total = 0
try: CN_total = PO.iloc[next_non_empty(PO, "中国总数量", "row", 2)]
except (KeyError, IndexError): CN_total = 0
destination = PO[PO.applymap(lambda x: '总数量' in str(x))].stack().tolist()
print(total, CA_total, UK_total, DE_total, CN_total, destination)

4118 3706 206 206 0 ['订单总数量 OrderTotal：', '订单 \n总数量', '加拿大总数量', '英国总数量', '德国总数量', '总数量 Total Qty： ']

In [236]:
(r, c) = PO.where(PO.eq('SKU')).stack().index.tolist()[0]
PO_detail = pd.DataFrame(data = PO.iloc[r+2:PO.shape[0], c:PO.shape[1]])
PO_detail.columns = PO.iloc[r, c:PO.shape[1]]
PO_detail = PO_detail.dropna(subset = 'SKU')
PO_detail.head()

8,SKU,Colour/Graphic,Colour/Graphic,Size,Design Version,OrderTotal,CA Total Qty,海运数量\nOcean Qty,海运数量\nOcean Qty,海运数量\nOcean Qty,UK Total Qty,UK Total Qty,UK Total Qty,UK Total Qty,DE Total Qty,DE Total Qty,DE Total Qty,DE Total Qty
10,WGS-NBB-M,Nebula Blue,恐龙蓝,M,NEW - 新款,300,270,270,NaN,NaN,15,15,NaN,NaN,15,15,NaN,NaN
11,WGS-NBB-L,Nebula Blue,恐龙蓝,L,NEW - 新款,238,216,216,NaN,NaN,11,11,NaN,NaN,11,11,NaN,NaN
12,WGS-NBB-XL,Nebula Blue,恐龙蓝,XL,NEW - 新款,212,192,192,NaN,NaN,10,10,NaN,NaN,10,10,NaN,NaN
13,WGS-WBY-M,Wildberry,紫红梅,M,NEW - 新款,300,270,270,NaN,NaN,15,15,NaN,NaN,15,15,NaN,NaN
14,WGS-WBY-L,Wildberry,紫红梅,L,NEW - 新款,238,216,216,NaN,NaN,11,11,NaN,NaN,11,11,NaN,NaN

In [231]:
cat_list = list(dict.fromkeys(PO_detail['SKU'].replace('-.*', '', regex = True).tolist()))
fac_list = [factory[x] for x in cat_list] 
cat = ' '.join(cat_list)
fac = ' '.join(fac_list)
try: name = PO.iloc[next_non_empty(PO, "Product Name", "col", 1)]
except (KeyError, IndexError): name = cat
print(cat, fac, name)

WGS JSTQ WGS